shadow service
megaease/easemesh pull request #75
Opened 2021-09-05 13:34 UTC by zouyingjie

1. emctl: add CURD processing for ShadowServices.
2. shadow service controller:  Create a copy of the service's Deployment or MeshDeployment based on shadow service.

2021-09-22 08:12 UTC, xxx7xxxx commented
@zouyingjie You need to fix the conflict

2021-09-24 06:06 UTC, zhao-kun requested changes
1. All source files haven't license declaration
2. Too many COPY codes, please remove them (you could introduce from original pkg via import ....) . **PLEASE DO NOT COPY/PAST CODE**
3.  Please fix complaints from the Github Action

2021-11-01 09:50 UTC, localvar commented on shadow/pkg/handler/deployment_cloner.go
> +			cloner.shadowDeploymentInitialize(nil)))(sourceDeployment, shadowService)
the long code line is hard to read, propose to split to short statements.
and it seems we don't need to use closure functions, they make code hard to read.

2021-11-01 09:50 UTC, localvar commented on shadow/pkg/handler/deployment_cloner.go
> +func (cloner *ShadowServiceCloner) shadowDeploymentInitialize(fn cloneDeploymentSpecFunc) cloneDeploymentSpecFunc {
parameter `fn` is not used.

2021-11-14 04:46 UTC, localvar approved these changes

2021-11-14 05:18 UTC, zhao-kun requested changes
Please provide unit tests, and make sure the coverage reaches 80% @zouyingjie

2021-11-26 02:24 UTC, zouyingjie commented on shadow/pkg/controller/shadowservice_controller.go
> +	// crdRestClient, err := utils.NewCRDRestClient()
Updated

2021-11-26 02:24 UTC, zouyingjie commented on shadow/pkg/controller/shadowservice_controller.go
> +// Do start shadow service sync and clone.
Updated

2021-11-26 02:24 UTC, zouyingjie commented on shadow/pkg/handler/deployment_cloner.go
> +
Updated

2021-11-26 02:25 UTC, zouyingjie commented on shadow/pkg/object/spec.go
> +	MySQL struct {
Updated

2021-11-26 02:32 UTC, xxx7xxxx approved these changes

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/controller/shadowservice_controller.go
> +	ShadowServiceKind = "ShadowService"
Fix complains

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/handler/clone_handler.go
> +type Cloner interface {
ditto

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/handler/delete_handler.go
> +	Separator = '/'
ditto

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/handler/deployment_cloner.go
> +	configJson, err := json.Marshal(config)
ditto

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/handler/search_handler.go
> +	MeshServiceAnnotation = "mesh.megaease.com/service-name"
ditto

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/object/spec.go
> +	Kafka struct {
ditto

2021-11-26 02:48 UTC, zhao-kun commented on shadow/pkg/object/spec.go
> +	Redis struct {
ditto

2021-11-26 06:13 UTC, zouyingjie commented on shadow/pkg/object/spec.go
> +	Redis struct {
updated

2021-11-26 06:13 UTC, zouyingjie commented on shadow/pkg/object/spec.go
> +	Kafka struct {
updated

2021-11-26 06:13 UTC, zouyingjie commented on shadow/pkg/controller/shadowservice_controller.go
> +	ShadowServiceKind = "ShadowService"
updated

2021-11-26 06:21 UTC, zhao-kun approved these changes

2021-11-26 06:22 UTC, merged